# Generated by Django 2.1.4 on 2018-12-18 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overflow_clone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overflowuser',
            name='favorites',
            field=models.ManyToManyField(blank=True, to='overflow_clone.Question'),
        ),
        migrations.AlterField(
            model_name='overflowuser',
            name='interests',
            field=models.ManyToManyField(blank=True, to='overflow_clone.Tag'),
        ),
        migrations.AlterField(
            model_name='overflowuser',
            name='reputation',
            field=models.IntegerField(blank=True),
        ),
    ]
