# Generated by Django 2.1.4 on 2019-01-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overflow_clone', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='vote',
        ),
        migrations.RemoveField(
            model_name='question',
            name='vote',
        ),
        migrations.AddField(
            model_name='comment',
            name='downvote',
            field=models.ManyToManyField(blank=True, related_name='comment_downvote', to='overflow_clone.OverflowUser'),
        ),
        migrations.AddField(
            model_name='comment',
            name='upvote',
            field=models.ManyToManyField(blank=True, related_name='comment_upvote', to='overflow_clone.OverflowUser'),
        ),
        migrations.AlterField(
            model_name='question',
            name='downvote',
            field=models.ManyToManyField(blank=True, related_name='question_downvote', to='overflow_clone.OverflowUser'),
        ),
        migrations.AlterField(
            model_name='question',
            name='upvote',
            field=models.ManyToManyField(blank=True, related_name='question_upvote', to='overflow_clone.OverflowUser'),
        ),
    ]
