# Generated by Django 2.1.4 on 2018-12-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overflow_clone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='vote',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='vote',
            field=models.IntegerField(default=0),
        ),
    ]
