# Generated by Django 2.1.4 on 2019-01-06 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overflow_clone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='vote',
            field=models.IntegerField(default=0),
        ),
    ]
