# Generated by Django 2.1.4 on 2019-01-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overflow_clone', '0002_auto_20190107_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='vote',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='vote',
            field=models.IntegerField(default=0),
        ),
    ]
