# Generated by Django 2.1.4 on 2018-12-19 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overflow_clone', '0002_auto_20181219_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overflowuser',
            name='reputation',
            field=models.IntegerField(default=0),
        ),
    ]
