# Generated by Django 2.1.4 on 2018-12-18 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overflow_clone', '0002_auto_20181218_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overflowuser',
            name='reputation',
            field=models.IntegerField(null=True),
        ),
    ]
