# Generated by Django 2.1.4 on 2019-01-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overflow_clone', '0003_auto_20181219_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='downvote',
            field=models.ManyToManyField(blank=True, related_name='downvote', to='overflow_clone.OverflowUser'),
        ),
        migrations.AddField(
            model_name='question',
            name='upvote',
            field=models.ManyToManyField(blank=True, related_name='upvote', to='overflow_clone.OverflowUser'),
        ),
        migrations.AlterField(
            model_name='question',
            name='vote',
            field=models.IntegerField(null=True),
        ),
    ]
