# Generated by Django 2.1.4 on 2019-01-07 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overflow_clone', '0003_auto_20190107_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='vote',
        ),
        migrations.RemoveField(
            model_name='question',
            name='vote',
        ),
    ]
