# Generated by Django 2.1.4 on 2019-01-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overflow_clone', '0004_auto_20190107_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.ManyToManyField(blank=True, related_name='question_answer', to='overflow_clone.Comment'),
        ),
    ]
